// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWAzZRQ7vXDfNIzNe70SACdOd4HQK2TkU',
    appId: '1:703408891579:web:e40ff5351d4ffb4528ab9e',
    messagingSenderId: '703408891579',
    projectId: 'fashion-store-app-8e11a',
    authDomain: 'fashion-store-app-8e11a.firebaseapp.com',
    storageBucket: 'fashion-store-app-8e11a.firebasestorage.app',
    measurementId: 'G-19S7CGEPZ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrpNrB25-iwxytiISHsHqOWssOG3oADGw',
    appId: '1:703408891579:android:5873fd012bdfbf5228ab9e',
    messagingSenderId: '703408891579',
    projectId: 'fashion-store-app-8e11a',
    storageBucket: 'fashion-store-app-8e11a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLYExn4513WvGn0dDOy3uXcq3_T5_D4M4',
    appId: '1:703408891579:ios:6dd83f7965037a6b28ab9e',
    messagingSenderId: '703408891579',
    projectId: 'fashion-store-app-8e11a',
    storageBucket: 'fashion-store-app-8e11a.firebasestorage.app',
    iosBundleId: 'com.example.fashionStoreApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLYExn4513WvGn0dDOy3uXcq3_T5_D4M4',
    appId: '1:703408891579:ios:6dd83f7965037a6b28ab9e',
    messagingSenderId: '703408891579',
    projectId: 'fashion-store-app-8e11a',
    storageBucket: 'fashion-store-app-8e11a.firebasestorage.app',
    iosBundleId: 'com.example.fashionStoreApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWAzZRQ7vXDfNIzNe70SACdOd4HQK2TkU',
    appId: '1:703408891579:web:a400ec918a25630728ab9e',
    messagingSenderId: '703408891579',
    projectId: 'fashion-store-app-8e11a',
    authDomain: 'fashion-store-app-8e11a.firebaseapp.com',
    storageBucket: 'fashion-store-app-8e11a.firebasestorage.app',
    measurementId: 'G-XQP8MTEX4B',
  );
}
